---
- name: Create user and add to sudoers on Debian servers
  hosts: debian_hosts
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure user 'master' exists and set password
      user:
        name: master
        password: "{{ 'Aa12356' | password_hash('sha512') }}"
        state: present
        groups: sudo
        append: yes

    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory

    - name: Add 'master' user to sudoers.d
      copy:
        dest: /etc/sudoers.d/master
        content: 'master ALL=(ALL) NOPASSWD:ALL'
        mode: '0440'
        validate: 'visudo -cf %s'
