---
- name: Remove user 'master' and its related changes on Debian servers
  hosts: debian_hosts
  become: yes
  tasks:
    - name: Remove 'master' from sudoers.d
      file:
        path: /etc/sudoers.d/master
        state: absent

    - name: Remove user 'master'
      user:
        name: master
        state: absent

    # The following task is optional. It doesn't actually revert package updates but serves as a placeholder.
    - name: "Revert package upgrade (Optional)"
      debug:
        msg: "Consider if you really want to revert package updates. This is just a placeholder task."
