---
- name: Remove user 'master' and its related changes on Debian servers
  hosts: debian_hosts
  become: yes
  tasks:
    - name: Remove 'master' from sudoers.d
      file:
        path: /etc/sudoers.d/master
        state: absent

    - name: Remove user 'master'
      user:
        name: master
        state: absent

    - name: Revert package upgrade (Optional: you might want to keep your packages updated)
      apt:
        upgrade: 'no'
