---
- name: Delete user 'master' from Debian servers
  hosts: debian_hosts
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Remove 'master' user from sudoers
      lineinfile:
        dest: /etc/sudoers
        line: 'master ALL=(ALL) NOPASSWD:ALL'
        state: absent
        validate: 'visudo -cf %s'

    - name: Delete user 'master'
      user:
        name: master
        state: absent
