---
- name: Perform health check for Netbox container
  hosts: localhost
  tasks:
    - name: Create the health directory if it does not exist
      file:
        path: /root/netbox/health
        state: directory
        mode: '0755'

    - name: Run health check on Netbox container
      shell: |
        docker inspect netbox-netbox-1 --format="{{ '{{json .State.Health}}' }}"
      register: health_check_output

    - name: Save health check output to file
      copy:
        content: "{{ health_check_output.stdout | to_nice_json }}"
        dest: /root/netbox/health/netbox_health_{{ ansible_date_time.date }}.txt
