---
- name: Fetch NetBox container health logs
  hosts: localhost
  tasks:
    - name: Ensure the health directory exists
      file:
        path: /root/netbox/health
        state: directory
        mode: '0755'

    - name: Run health check on NetBox container
      shell: |
        docker inspect netbox-netbox-1 --format="{{ '{{json .State.Health}}' }}"
      register: health_check_output
      failed_when: health_check_output.rc != 0

    - name: Parse health check output
      set_fact:
        health_parsed: "{{ health_check_output.stdout | from_json }}"
      when: health_check_output.stdout != ""

    - name: Extract and clean health check logs
      set_fact:
        cleaned_logs: >
          {% for log in health_parsed.Log %}
          - Start: {{ log.Start }}
            End: {{ log.End }}
            Exit Code: {{ log.ExitCode }}
            Output: {{ log.Output | regex_replace('<[^>]*>', '') | regex_replace('\\s+', ' ') }}
          {% endfor %}
      when: health_parsed is defined and health_parsed.Log | length > 0

    - name: Save health logs to a file
      copy:
        content: |
          Health Check Report - NetBox
          ========================================
          Health Status: {{ health_parsed.Status | default('Unknown') }}
          Failing Streak: {{ health_parsed.FailingStreak | default('Unknown') }}
          Logs:
          {{ cleaned_logs | default('No logs available') }}
        dest: /root/netbox/health/netbox_health_{{ ansible_date_time.date }}.txt
      delegate_to: localhost
      when: health_parsed is defined
