---
- name: Perform health check for Netbox container
  hosts: localhost
  tasks:
    - name: Create the health directory if it does not exist
      file:
        path: /root/netbox/health
        state: directory
        mode: '0755'

    - name: Run health check on Netbox container
      shell: |
        docker inspect netbox-netbox-1 --format="{{ '{{json .State.Health}}' }}"
      register: health_check_output

    - name: Parse health check output
      set_fact:
        health_parsed: "{{ health_check_output.stdout | from_json }}"

    - name: Extract and save health status
      copy:
        content: |
          Health Status: {{ health_parsed.Status }}
          Failing Streak: {{ health_parsed.FailingStreak }}
          Logs:
          {% for log in health_parsed.Log %}
            - Start: {{ log.Start }}
              End: {{ log.End }}
              Exit Code: {{ log.ExitCode }}
              Output: {{ log.Output | regex_replace('\\s+', ' ') }}
          {% endfor %}
        dest: /root/netbox/health/netbox_health_{{ ansible_date_time.date }}.txt
